obj-m := primes.o primes-atomic.o

clean:
	rm -f modules.order  Module.symvers
	rm -f primes.ko  primes.mod.c  primes.mod.o  primes.o
	rm -f primes-atomic.ko  primes-atomic.mod.c  primes-atomic.mod.o  primes-atomic.o
